# Generated by Django 3.2.12 on 2022-03-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRateLookUp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('o_id', models.IntegerField()),
                ('o_city', models.TextField(blank=True, max_length=255, null=True)),
                ('o_state', models.TextField(blank=True, max_length=255, null=True)),
                ('o_country', models.TextField(blank=True, max_length=255, null=True)),
                ('o_location', models.TextField(blank=True, max_length=255, null=True)),
                ('o_zip_code', models.IntegerField()),
                ('o_transporation_type', models.TextField(blank=True, max_length=255, null=True)),
                ('o_company', models.TextField(blank=True, max_length=255, null=True)),
                ('o_weight', models.FloatField()),
                ('o_volume', models.FloatField()),
                ('o_rate', models.FloatField()),
                ('s_id', models.IntegerField()),
                ('s_city', models.TextField(blank=True, max_length=255, null=True)),
                ('s_state', models.TextField(blank=True, max_length=255, null=True)),
                ('s_country', models.TextField(blank=True, max_length=255, null=True)),
                ('s_location', models.TextField(blank=True, max_length=255, null=True)),
                ('s_zip_code', models.IntegerField()),
                ('s_transporation_type', models.TextField(blank=True, max_length=255, null=True)),
                ('s_company', models.TextField(blank=True, max_length=255, null=True)),
                ('s_weight', models.FloatField()),
                ('s_volume', models.FloatField()),
                ('s_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
